apiVersion: v1
kind: Service
metadata:
  name: {{ include "imgserver.fullname" . }}
  labels:
    {{- include "imgserver.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{.Values.service.hostname}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodeport }}
      nodePort: {{.Values.service.nodeport}}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "imgserver.selectorLabels" . | nindent 4 }}
