apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: img-server
  name: img-service
spec:
  ports:
  - port: 3333
    protocol: TCP
    nodePort: 32000
  selector:
    app: img-server
  type: NodePort
status:
  loadBalancer: {}
